1. Numpy ile Matris İşlemleri
- 5x5 boyutunda rastgele (0-100 arasında) tam sayılardan oluşan bir matris oluşturun.
- Bu matrisin:
  • Ortalama, standart sapma ve varyansını hesaplayın.
  • En büyük ve en küçük değerlerini bulun.
  • Köşegenindeki elemanların toplamını bulun


In [1]:
import numpy as np
np.random.seed(42)
matris = np.random.randint(0, 109, size=(5, 5))
print("5x5 Rastgele Matris:")
print(matris)

5x5 Rastgele Matris:
[[102  51  92  14 106]
 [ 71  60  20 102  82]
 [ 86  74  74  87  99]
 [103  23   2  21  52]
 [  1  87 107  29  37]]


In [27]:
print("\nOrtalama:",np.mean(matris))
print("Standart Sapma:",np.std(matris))
print("Varyans:",np.var(matris) )
print("En Büyük Değer:", np.max(matris))
print("En Küçük Değer:", np.min(matris))
print("Köşegen Toplamı:", np.trace(matris))


Ortalama: 63.28
Standart Sapma: 34.753440117490534
Varyans: 1207.8016000000002
En Büyük Değer: 107
En Küçük Değer: 1
Köşegen Toplamı: 294


2. Numpy ile Veri Simülasyonu
- 1000 adet öğrencinin sınav puanlarını (0-100 arası, normal dağılımdan gelen) simüle edin.
- Ortalama, medyan ve standart sapmayı hesaplayın.
- 50’den düşük alan kaç öğrenci olduğunu bulun.


In [31]:
puanlar = np.random.normal(75, 15, 1000)
puanlar = np.clip(puanlar, 0, 100).astype(int)
print("Ortalama:", np.mean(puanlar))
print("Medyan:", np.median(puanlar))
print("Standart Sapma:", np.std(puanlar))
print("50'den Düşük Alan Öğrenci Sayısı:", np.sum(puanlar < 50))

Ortalama: 75.304
Medyan: 76.0
Standart Sapma: 14.564051084777201
50'den Düşük Alan Öğrenci Sayısı: 51


Bir CSV dosyası oluşturun ya da aşağıdaki gibi örnek bir DataFrame hazırlayın:
Öğrenci	Yaş	Bölüm	Matematik	Fizik	Kimya
Ali 	20	Bilgisayar	70	    65	    80
Ayşe	21	Fizik	    60	    75	    85
Mehmet	19	Kimya	    80	    70	    65
Zeynep	22	Bilgisayar	90	    85	    95
Ahmet	20	Fizik	    55	    60	    70


1.Veri setini Pandas DataFrame olarak oluşturun.
2.Her ders için ortalama puanı bulun.
3.En yüksek matematik notunu alan öğrenciyi bulun.
4.Her öğrencinin not ortalamasını hesaplayan yeni bir sütun ekleyin.
5.Bölümlere göre gruplayarak her bölümün ortalama başarılarını hesaplayın.
6.Ortalaması 70’in üzerinde olan öğrencileri filtreleyin


In [57]:
#1.
import pandas as pd
data = {
    'Öğrenci': ['Ali', 'Ayşe', 'Mehmet', 'Zeynep', 'Ahmet'],
    'Yaş': [20, 21, 19, 22, 20],
    'Bölüm': ['Bilgisayar', 'Fizik', 'Kimya', 'Bilgisayar', 'Fizik'],
    'Matematik': [70, 60, 80, 90, 55],
    'Fizik': [65, 75, 70, 85, 60],
    'Kimya': [80, 85, 65, 95, 70]
}
df = pd.DataFrame(data)

In [59]:
#2.
print("Ders Ortalamaları:")
print(df['Matematik'].mean())
print(df['Fizik'].mean())
print(df['Kimya'].mean())

Ders Ortalamaları:
71.0
71.0
79.0


In [61]:
#3.
max_mat = df['Matematik'].max()
print("En Yüksek Matematik Puanı:", max_mat)
en_iyi = df[df['Matematik'] == max_mat]
print("Öğrenci:", en_iyi['Öğrenci'].values[0])

En Yüksek Matematik Puanı: 90
Öğrenci: Zeynep


In [63]:
#4.
df['Ortalama'] = (df['Matematik'] + df['Fizik'] + df['Kimya']) / 3  # Manuel ortalama, kolay!
print("Yeni Tablo (Ortalama Eklenmiş):")
print(df)

Yeni Tablo (Ortalama Eklenmiş):
  Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya   Ortalama
0     Ali   20  Bilgisayar         70     65     80  71.666667
1    Ayşe   21       Fizik         60     75     85  73.333333
2  Mehmet   19       Kimya         80     70     65  71.666667
3  Zeynep   22  Bilgisayar         90     85     95  90.000000
4   Ahmet   20       Fizik         55     60     70  61.666667


In [67]:
#5.soruyu yapamadım


In [65]:
#6.
iyi_ogrenciler = df[df['Ortalama'] > 70]
print("70 Üstü Öğrenciler:")
print(iyi_ogrenciler[['Öğrenci', 'Ortalama']])

70 Üstü Öğrenciler:
  Öğrenci   Ortalama
0     Ali  71.666667
1    Ayşe  73.333333
2  Mehmet  71.666667
3  Zeynep  90.000000
