Yaz Kampı: Veri Bilimi – Hafta 3

In [1]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz = list(set(notlar))
print("Benzersiz Notlar:", benzersiz)

en_yuksek = max(notlar)
en_dusuk = min(notlar)
print("En yüksek not:", en_yuksek)
print("En düşük not:", en_dusuk)

sirali = sorted(notlar)
print("Sıralı Notlar:", sirali)

Benzersiz Notlar: [100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Sıralı Notlar: [76, 76, 85, 85, 92, 92, 92, 100]


In [1]:
def armstrong_mu(sayi):
    sayi_str = str(sayi)
    toplam = 0
    for basamak in sayi_str:
        toplam = toplam + int(basamak) ** 3
    if toplam == sayi:
        return True
    else:
        return False

print("153 Armstrong mu?", armstrong_mu(153)) 
print("100 Armstrong mu?", armstrong_mu(100)) 

153 Armstrong mu? True
100 Armstrong mu? False


In [ ]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
ortak = A & B
sadece_A = A - B
birlesim = A | B
birlesim_list = list(birlesim) 
birlesim_list.sort()           
print("Ortak diller:", ortak)
print("Sadece A'da olan diller:", sadece_A)
print("Birleşim (alfabetik):", birlesim_list)

In [ ]:
import random
import statistics
sayilar = []
for i in range(10):
    sayilar.append(random.randint(1, 100))
print("Rastgele sayılar:", sayilar)
ortalama = statistics.mean(sayilar)
std_sapma = statistics.pstdev(sayilar)
print("Ortalama:", ortalama)
print("Standart sapma:", round(std_sapma, 2))


In [2]:
# Fonksiyon tanımlıyoruz
def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam_kelime_sayisi = len(kelimeler)
    en_uzun_kelime = max(kelimeler, key=len)
    kelime_siklik = {}
    for kelime in kelimeler:
        kelime = kelime.lower()  # Büyük/küçük harfi yok saymak için
        if kelime in kelime_siklik:
            kelime_siklik[kelime] += 1
        else:
            kelime_siklik[kelime] = 1
    en_sik_kelime = max(kelime_siklik, key=kelime_siklik.get)
    return toplam_kelime_sayisi, en_uzun_kelime, en_sik_kelime


metin =str(input("Metni giriniz: "))
toplam, en_uzun, en_sik = kelime_sayaci(metin)
print("Toplam kelime sayısı:", toplam)
print("En uzun kelime:", en_uzun)
print("En sık geçen kelime:", en_sik)

Toplam kelime sayısı: 4
En uzun kelime: programalama
En sık geçen kelime: python


In [3]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x**2, cift_sayilar))
kareler_desc = sorted(kareler, reverse=True)
print("Çift sayılar:", cift_sayilar)
print("Kareleri:", kareler)
print("Kareleri azalan sırada:", kareler_desc)

Çift sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Kareleri azalan sırada: [576, 324, 256, 144]


In [4]:

def rakamlari_topla(metin):
    toplam = 0
    rakam = ""
    for karakter in metin:
        if karakter.isdigit():
            rakam += karakter 
        else:
            if rakam != "":
                toplam += int(rakam)
                rakam = ""  
    if rakam != "":
        toplam += int(rakam) 
    return toplam
metin = "abc12def3"
sonuc = rakamlari_topla(metin)
print("Rakamların toplamı:", sonuc)


Rakamların toplamı: 15


In [5]:
import numpy as np
dizi = np.random.randint(0, 51, size=10)
ortalama = np.mean(dizi)
std_sapma = np.std(dizi)
en_buyuk = np.max(dizi)
print("Dizi:", dizi)
print("Ortalama:", ortalama)
print("Standart Sapma:", std_sapma)
print("En Büyük Değer:", en_buyuk)

Dizi: [32 41 17 48 32 10 25 43 46 17]
Ortalama: 31.1
Standart Sapma: 12.762836675285005
En Büyük Değer: 48


In [6]:
import numpy as np
matris = np.random.rand(5, 5)
sutun_ort = np.mean(matris, axis=0)  
binary_matris = np.where(matris > 0.5, 1, 0)
print("Orijinal Matris:\n", matris)
print("Sütun Ortalamaları:", sutun_ort)
print("Binary Matris:\n", binary_matris)

Orijinal Matris:
 [[0.2614076  0.86713058 0.96655916 0.53733285 0.29061333]
 [0.99855367 0.67719776 0.08772182 0.30228514 0.74434655]
 [0.96819731 0.93350401 0.67995384 0.68093875 0.36613243]
 [0.24299972 0.34549081 0.63156164 0.89305152 0.89749587]
 [0.00715928 0.32492314 0.69388397 0.84223845 0.37570176]]
Sütun Ortalamaları: [0.49566352 0.62964926 0.61193609 0.65116934 0.53485799]
Binary Matris:
 [[0 1 1 1 0]
 [1 1 0 0 1]
 [1 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]]
